# https://docs.readthedocs.io/en/latest/yaml-config.html
version: 2

formats:
  - htmlzip
  - epub

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.13"

python:
  install:
    - requirements: docs-requirements.txt

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true
